model:
  latent_size: 16
  channels_in: 4
  patch_size: 4
  hidden_size: 128
  num_features: 128
  num_layers: 15
  num_heads: 8

diffusion:
  num_timesteps: 1000
  betas: [0.0001, 0.02] 

optimizer:
  lr: 1e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

train:
  epochs: 200
  amp: true
  grad_clip: 1.0
  warmup_ratio: 0.03
  seed: 42
  checkpoint_path: "last.ckpt"

eval:
  num_samples: 8
  sample_images_path: "generated_samples.jpg"

data:
  img_path: "CelebAMask-HQ/CelebA-HQ-img"
  latent_path: "latents_pkl"   
  batch_size: 64
  num_workers: 4
  pin_memory: true
  shuffle: true

wandb:
  logging: false
  project_name: "miniDiT"
  run_name: None

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true